# Made with ❤️ by Devin

########################################
#                                      #
#            SERVER CONFIG             #
#                                      #
########################################

server:
  id: ''
  owner: ''