#######################################
#                                     #
#             MAIN CONFIG             #
#                                     #
#######################################

#######################################
#                                     #
#            SERVER CONFIG            #
#                                     #
#######################################


server:
  id: '763217323556995082'
  owner: '384010503824867328'

welcome:
  embed: false # true = embed will be sent instead of a message; false = the message below will send
  message: 'This is a welcome message'
  channel: '763218574336458753'