# Made with ❤️ by Devin

########################################
#                                      #
#             DO NOT SHARE             #
#                                      #
########################################

TOKEN: 'OTQ2ODU3NDc2ODExMjU5OTA0.Yhkzvg.Ts7uF4w3CXVHeVt65y4duKA2_mE' # Token for the bot